# Generated by Django 5.0.2 on 2025-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_APP', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
